### ISSUE TITLE
Add a way to target alternate MySQL instances

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt/caboose#8]
Because Pantheon currently throttles site clone workflow ops to one per site at any given time, it would be useful to allow caboose to target MySQL instances other than the current Drupal site's (e.g., a remote Pantheon MySQL container).

Adding this would work around Pantheon's limitation and allow ad-hoc Pantheon multidev environment refreshing without holding up other, possibly more important, site clone workflow ops.

**Comment by doublejosh** [comment]
invalidating due to inactivity
